server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
    
spring:
  package-version: 1.0.0
  web:
    resources:
      static-locations: file:/home
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    username: tmasolutions25year@gmail.com
    password: mztofcxsybzexgpq
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
    transport:
      protocol: smtp
  data:
    redis:
      database: 0
      port: 6379
      timeout: 30000
      host: 192.168.121.32
      username: default
      password: 12345678x@X
  mongodb:
    host: 192.168.121.22
    port: 27017
    username: mongouser
    password: 1_Abc_123@
    authentication-database: admin
  session:
    store-type: redis
    redis:
      namespace: dev
  cache:
    type: redis
    redis:
      time-to-live: '45000'
      cache-null-values: 'true'
  jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                id:
                    new_generator_mappings: false

kafka:
  bootstrapAddress: 192.168.121.24:9092
  listener:
    enabled: true
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
  groups:
    create-sso-account: ${CREATE_SSO_ACCOUNT_ID:create-account-group-crm-prod}
    update-sso-account: ${UPDATE_SSO_ACCOUNT_ID:update-account-group-crm-prod}
    delete-sso-account: ${DELETE_SSO_ACCOUNT_ID:delete-account-group-crm-prod}
    sync-account-topic: sync-account-group-crm-prod
  topics:
    create-account-topic: create-account-topic-prod
    update-account-topic: update-account-topic-prod
    delete-account-topic: delete-account-topic-prod
    sync-account-topic: sync-account-topic-prod
    create-customer-topic: create-customer-topic-prod
    create-product-topic: create-product-topic-prod
    create-contract-topic: create-contract-topic-prod
    update-customer-topic: update-customer-topic-prod
    update-product-topic: update-product-topic-prod
    update-contract-topic: update-contract-topic-prod
    delete-customer-topic: delete-customer-topic-prod
    delete-product-topic: delete-product-topic-prod
    delete-contract-topic: delete-contract-topic-prod
    send-customer-sms-for-marketing-topic: send-customer-sms-for-marketing-topic-prod
    cancel-send-customer-sms-for-marketing-topic: cancel-send-customer-sms-for-marketing-topic-prod
    send-customer-email-for-survey-topic: send-customer-email-for-survey-topic-prod
    send-user-email-for-survey-topic: send-user-email-for-survey-topic-prod
    send-guest-email-for-survey-topic: send-guest-email-for-survey-topic-prod
    schedule-send-mail-topic: schedule-send-mail-topic-prod
    cancel-schedule-send-mail-topic: cancel-schedule-send-mail-topic-prod
    test-send-mail-topic: test-send-mail-topic-prod
    send-mail-topic: send-mail-topic-prod

sending-survey-email-url: "https://crm-live.tma-swerp.com/survey-form?"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      instance-id: localhost:${server.port}
  
management:
  tracing:
    sampling:
      probability: 1.0

logging:        
  file:
    name: application.log
  level:
    root: INFO
    org.springframework: INFO

es:
  hostname: 192.168.121.46
  port: 9200
  username: elastic
  password: 12345678x@X

referent-link:
  product: main/listCustomer/
  customer: main/listProduct/
  contract: main/listContract/

users:
  sync:
    schedule:
      time: 0 0 2 * * ?
      time-zone: Asia/Ho_Chi_Minh
schedule:
  email:
    customer-care:
      time : 0 0 0 * * ?
      zone : Asia/Ho_Chi_Minh


app:
  client:
    domain: http://dev-sso.tma-swerp.com
  gateway:
    domain-name: https://api-swwebdeverp-develop.tma-swerp.com

jwt:
  accessTokenExpired: 602
  refreshTokenExpired: 720022424
key:
  forgot-password-expired: 300
